### ISSUE TITLE
Выкатывание библиотеки в Releases с новой версией

### ISSUE THREAD

**Issue by mnb3000** [k-egor-smirnov/vk-next#2]
Было бы идеально при апдейте версии выкатывать новую версию в релизы гитхаба с ченджлогом. А если был бы npm пакет - было бы еще лучше

**Comment by k-egor-smirnov** [comment]
Приму к сведению, а npm-пакет уже есть - https://www.npmjs.com/package/vk-next. Баджик уже етсь README в dev ветке

**Comment by k-egor-smirnov** [comment]
Все версии также перенесены в релизы
https://github.com/k-egor-smirnov/vk-next/releases/tag/0.0.3
